"""Add UserSession model

Revision ID: 45a3ae5f1bda
Revises: 744834877a35
Create Date: 2025-05-13 20:58:35.073292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45a3ae5f1bda'
down_revision = '744834877a35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_student', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
