"""Add UserSession model

Revision ID: 4c6298d081a3
Revises: 45a3ae5f1bda
Create Date: 2025-05-13 21:47:31.802156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c6298d081a3'
down_revision = '45a3ae5f1bda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
