"""Add UserSession model

Revision ID: 744834877a35
Revises: 03f3b4c45428
Create Date: 2025-05-13 19:11:39.947765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '744834877a35'
down_revision = '03f3b4c45428'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_student',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'student_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_student')
    # ### end Alembic commands ###
