"""Add choices to quiz_question

Revision ID: 753ef9686abb
Revises: 4844813aba9d
Create Date: 2025-05-09 11:14:03.527927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753ef9686abb'
down_revision = '4844813aba9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('choice_a', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('choice_b', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('choice_c', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('correct_choice', sa.String(length=1), nullable=False))
        batch_op.add_column(sa.Column('student_choice', sa.String(length=1), nullable=True))
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('student_answer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_answer', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('correct_answer', sa.TEXT(), nullable=False))
        batch_op.drop_column('student_choice')
        batch_op.drop_column('correct_choice')
        batch_op.drop_column('choice_c')
        batch_op.drop_column('choice_b')
        batch_op.drop_column('choice_a')

    # ### end Alembic commands ###
