"""Add choices to quiz_question

Revision ID: 7b36f2aee384
Revises: 753ef9686abb
Create Date: 2025-05-13 17:06:30.136366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b36f2aee384'
down_revision = '753ef9686abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_first_login', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('groq_api_key', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('groq_api_key')
        batch_op.drop_column('is_first_login')

    # ### end Alembic commands ###
