"""Add cascade delete to Document-Quiz relationship

Revision ID: d60dff2ee16c
Revises: 236dd8a71e39
Create Date: 2025-04-15 13:14:03.322073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd60dff2ee16c'
down_revision = '236dd8a71e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('document_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.alter_column('document_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
